In [ ]:
import torch

In [ ]:
rand =torch.randn(3,4)

In [ ]:
rand

tensor([[ 1.2040,  2.4724,  0.1865,  1.0104],
        [-0.5174, -0.1630,  0.0544, -0.8530],
        [ 1.5659,  0.4878,  1.7584,  1.3391]])

In [ ]:
rand[1,2]

tensor(0.0544)

In [ ]:
randint= torch.randint(low=1,high=50,size=(3,4))

In [ ]:
randint

tensor([[49, 43,  1, 35],
        [33, 32, 21, 43],
        [17, 21, 39, 42]])

In [ ]:
torch.exp(randint)

tensor([[1.9073e+21, 4.7278e+18, 2.7183e+00, 1.5860e+15],
        [2.1464e+14, 7.8963e+13, 1.3188e+09, 4.7278e+18],
        [2.4155e+07, 1.3188e+09, 8.6593e+16, 1.7393e+18]])

In [ ]:
x=torch.arange(12,dtype=torch.float32).reshape(3,4)
y= torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [ ]:
x,y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

**Concatenation of tensors**

In [ ]:
torch.cat((x,y)) #by default is the dim=0

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [ ]:
torch.cat((x,y),dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [ ]:
torch.cat((x,y),dim=1) #along the columns

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [ ]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
x.sum(),y.sum()

(tensor(66.), tensor(30.))

**Broadcasting**

In [ ]:
a= torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a.shape,b.shape

(torch.Size([3, 1]), torch.Size([1, 2]))

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
o=torch.zeros(3).reshape(3,1)
o

tensor([[0.],
        [0.],
        [0.]])

In [ ]:
o+b

tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
a=a.numpy()

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a=torch.from_numpy(a)

In [ ]:
type(a)

torch.Tensor

In [ ]:
a==b

tensor([[ True, False],
        [False,  True],
        [False, False]])

In [ ]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
y

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [ ]:
x<y,x==y,x>y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [ ]:
x.transpose(0,1) #fot transposition.

tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])

In [ ]:
x.flatten().reshape(2,2,3) #flatten() is used to change n-D tensor to 1-D tensor.

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

**Coonecting to Drive**

In [ ]:
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os

file_path = '/content/drive/MyDrive/D2L/d2l_house.csv'

# Create the directory if it doesn't exist
os.makedirs(os.path.dirname(file_path), exist_ok=True)


In [ ]:
with open(file_path,'w') as f:
  f.write('''NumRooms,RoofType,Price
  NA,NA,127500
  2,NA,106000
  4,Slate,178100
  NA,NA,140000''')

**Pandas**

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv(file_path)

In [ ]:
data.head()

NumRooms RoofType   Price
0       NA      NaN  127500
1        2      NaN  106000
2        4    Slate  178100
3       NA      NaN  140000

In [ ]:
d=data.dropna(axis=1,inplace=True)

In [ ]:
data

NumRooms   Price
0       NA  127500
1        2  106000
2        4  178100
3       NA  140000

**Linear Algebra**

In [ ]:
# Scalers
x=torch.tensor(3)
y=torch.tensor(6.7)

In [ ]:
x,y

(tensor(3), tensor(6.7000))

**Vectors**

In [ ]:
x=torch.arange(3)
x

tensor([0, 1, 2])

In [ ]:
x[2]

tensor(2)

In [ ]:
len(x)

3

In [ ]:
A = torch.arange(6,dtype=torch.float32).reshape(2,3)
B =A.clone()

A,A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [ ]:
B

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [ ]:
A+3

tensor([[3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
A,A.sum()

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor(15.))

In [ ]:
A,A.sum(axis=0,keepdim=True),A.sum(axis=1,keepdim=True)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[3., 5., 7.]]),
 tensor([[ 3.],
         [12.]]))

In [ ]:
A.flatten().sum()

tensor(15.)

In [ ]:
A.mean()

tensor(2.5000)

In [ ]:
A.sum()/A.numel()

tensor(2.5000)

In [ ]:
A,A.cumsum(axis=0),A.cumsum(axis=1)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 5., 7.]]),
 tensor([[ 0.,  1.,  3.],
         [ 3.,  7., 12.]]))

In [ ]:
m,n = torch.arange(3),torch.arange(3,6,1)

In [ ]:
m,n

(tensor([0, 1, 2]), tensor([3, 4, 5]))

In [ ]:
d= torch.dot(m,n)

In [ ]:
d

tensor(14)

In [ ]:
p = torch.arange(12).reshape(4,3)
q =torch.arange(12,24,1).reshape(3,4)

In [ ]:
p,q

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]))

In [ ]:
r = torch.matmul(p,q,out=None)

In [ ]:
r

tensor([[ 56,  59,  62,  65],
        [200, 212, 224, 236],
        [344, 365, 386, 407],
        [488, 518, 548, 578]])

In [ ]:
p,x

(tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]),
 tensor([0, 1, 2]))

In [ ]:
p@x,torch.mv(p,x)

(tensor([ 5, 14, 23, 32]), tensor([ 5, 14, 23, 32]))

In [ ]:
mm = torch.mm(p,q)

In [ ]:
mm

tensor([[ 56,  59,  62,  65],
        [200, 212, 224, 236],
        [344, 365, 386, 407],
        [488, 518, 548, 578]])

In [ ]:
l = torch.tensor([7,-9],dtype=torch.float32)

In [ ]:
torch.norm(l)

tensor(11.4018)

In [ ]:
mm,mm/mm.sum(axis=1),mm.sum(axis=1)

(tensor([[ 56,  59,  62,  65],
         [200, 212, 224, 236],
         [344, 365, 386, 407],
         [488, 518, 548, 578]]),
 tensor([[0.2314, 0.0677, 0.0413, 0.0305],
         [0.8264, 0.2431, 0.1491, 0.1107],
         [1.4215, 0.4186, 0.2570, 0.1909],
         [2.0165, 0.5940, 0.3648, 0.2711]]),
 tensor([ 242,  872, 1502, 2132]))